name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to DigitalOcean
        uses: appleboy/ssh-action@master
        with:
          host: 157.245.218.43
          username: root
          key: ${{ secrets.DROPLET_SSH_KEY }}
          script: |
            cd /var/www/mcp-app
            chmod +x scripts/deploy.sh
            ./scripts/deploy.sh 